### ISSUE TITLE
Coloring books

### ISSUE THREAD

**Issue by h3nri** [hua1995116/GPTsEasy#1]
**Title**

Coloring books

**Describe**

Create your own coloring book that is perfect for kids and adults alike. Choose your design, complexity and dive into the world of fun and creativity!

**Usage**

[chatgpt links](https://chat.openai.com/g/g-3AIHQiO1r-coloring-books)

**Links**

[twitter](https://twitter.com/Jind_Rich)

**Comment by hua1995116** [comment]
done
